_wandb:
    value:
        cli_version: 0.23.1
        e:
            y8njwkf37mvh0hr1is7pyceawjegjjam:
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "39843287662592"
                        used: "19216675897344"
                email: fengli1702@gmail.com
                executable: /usr/local/bin/python
                git:
                    remote: https://github.com/vllm-project/vllm.git
                gpu: NVIDIA H200
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-967cdcf6-43c4-c8ce-6c7a-d9cdbbd37d77
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-7302451d-9342-ea40-a113-3a4e0872aeca
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-a4c23cef-f2f2-4528-7092-11b569e23985
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-9c505405-1d92-eeca-909e-7ef684eb7196
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-051dc7a0-39ec-d7e5-55ce-fbd99802d713
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-6b9761c5-beeb-b620-45cf-7fef8ebc6aeb
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-b929d321-5037-cb9b-728a-d58621149726
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-9032fd52-bd9f-22c0-eea2-37c118ce21aa
                host: 19ae480b7ae7
                memory:
                    total: "1622438174720"
                os: Linux-5.14.0-611.27.1.el9_7.x86_64-x86_64-with-glibc2.35
                program: <stdin>
                python: CPython 3.11.14
                root: /workspace/vllm
                startedAt: "2026-03-17T05:52:42.563306Z"
                writerId: y8njwkf37mvh0hr1is7pyceawjegjjam
        m: []
        python_version: 3.11.14
        t:
            "3":
                - 2
                - 13
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
